### PR TITLE
New set of sympy's fixes

### PR DESCRIPTION
**Pull request by skirpichev**
- [x] sympy/sympy#9441 no, new feature, very questionable;  svg may be ok, but with printers!
- [x] sympy/sympy#9468
- [x] sympy/sympy#7860
- [x] sympy/sympy#9455
- [x] sympy/sympy#8793: feature, no
- [x] sympy/sympy#9211: no, crap
- [x] sympy/sympy#9188: no, physics
- [x] sympy/sympy#9492: no, new new assumptions
- [x] sympy/sympy#9499: no, AUTHORS
- [x] sympy/sympy#9493: already in
- [x] sympy/sympy#9429: no, not an important optimization
- [x] sympy/sympy#9387
- [x] sympy/sympy#9376: already in
- [x] sympy/sympy#8941: no, should this return just an Expr?
- [x] sympy/sympy#9055
- [x] sympy/sympy#9186: check that, but right now it looks ugly
- [x] sympy/sympy#9485
- [x] sympy/sympy#9061
- [x] sympy/sympy#9502
- [x] sympy/sympy#8577 no
- [x] sympy/sympy#9460
- [x] sympy/sympy#9514
- [x] sympy/sympy#9103 no, but think about
- [x] sympy/sympy#9496
- [x] sympy/sympy#9435 no, sequences
- [x] sympy/sympy#9524 no, solveset
- [x] sympy/sympy#9517
- [x] sympy/sympy#9372
- [x] sympy/sympy#9489 we have no needs to split tests at all...
- [x] sympy/sympy#9530
- [x] sympy/sympy#9370
- [x] sympy/sympy#9528
- [x] sympy/sympy#9535
- [x] sympy/sympy#9548
- [x] sympy/sympy#9527
- [x] sympy/sympy#9463 no, ComplexPlane.  just a crap, starting from the name
- [x] sympy/sympy#9518
- [x] sympy/sympy#8731, no: my target audience know Python
- [x] sympy/sympy#9434
- [x] sympy/sympy#9124
- [x] sympy/sympy#9552 no
- [x] sympy/sympy#9117
- [x] sympy/sympy#9537
- [x] sympy/sympy#9520
- [x] sympy/sympy#9553
- [x] sympy/sympy#9574: no, solveset
- [x] sympy/sympy#9566: no, new crap for series
- [x] sympy/sympy#9562: no, new crap for new new assumptions
- [x] sympy/sympy#9438: linear solvers, review!  bad (moar linear solvers?)
- [x] sympy/sympy#9526: partially good
- [x] sympy/sympy#9596, testing: I did this already
- [x] sympy/sympy#9602 no, authors
- [x] sympy/sympy#9589 no, solveset
- [x] sympy/sympy#9603 no, authors
- [x] sympy/sympy#9570 no, solveset
- [x] sympy/sympy#9540 no, see https://github.com/skirpichev/omg/pull/112
- [x] sympy/sympy#9595
- [x] sympy/sympy#9612 no, solveset
- [x] sympy/sympy#9621 no, solveset
- [x] sympy/sympy#9437 with a better fix
- [x] sympy/sympy#9575 no, new crap for series
- [x] sympy/sympy#9622 
- [x] sympy/sympy#9625, no, another piece of crap from @aktech & co
- [x] sympy/sympy#9560, no, another unreviewed "feature" from @asmeurer 
- [x] sympy/sympy#9592, no, new assumptions
- [x] sympy/sympy#9490, no, nonzero not imply real
- [x] sympy/sympy#9525
- [x] sympy/sympy#9613, no, sequences
- [x] sympy/sympy#9523, no, series
- [x] sympy/sympy#9626, no: bad math (assume real args)
- [x] sympy/sympy#9627: this should go to #112
- [x] sympy/sympy#9618 no, solveset
- [x] sympy/sympy#8602
- [x] sympy/sympy#9495 no, series
- [x] sympy/sympy#9513 no, physics
- [x] sympy/sympy#9590 no, sequences
- [x] sympy/sympy#9640 no, series
- [x] sympy/sympy#9600
- [x] sympy/sympy#9645
- [x] sympy/sympy#9546
- [x] sympy/sympy#9649 no authors
- [x] sympy/sympy#9108 no, preview
- [x] sympy/sympy#9663
- [x] sympy/sympy#9662
- [x] sympy/sympy#9656
- [x] sympy/sympy#9657
- [x] sympy/sympy#9633 no, feature
- [x] sympy/sympy#9655 no, physics
- [x] sympy/sympy#9653 no, physics
- [x] sympy/sympy#9582, no: nonzero does not imply real
- [x] sympy/sympy#9475, no, new assumptions
- [x] sympy/sympy#8856, no, anaconda PR
- [x] sympy/sympy#9581
- [x] sympy/sympy#9647
- [x] sympy/sympy#8506 no, questionable optimization
- [x] sympy/sympy#9599 things going to be really bad...
- [x] sympy/sympy#9615, no, another piece of crap from "reviewers".  But I should fix rsolve.
- [x] sympy/sympy#9679, authors
- [x] sympy/sympy#9676, no, removing Q.infinitesimal
- [x] sympy/sympy#9670: goes to #34
- [x] sympy/sympy#9643 no, series
- [x] sympy/sympy#9688 no, solveset
- [x] sympy/sympy#9690 no, solveset
- [x] sympy/sympy#9666 no, ComplexPlane
- [x] sympy/sympy#9668 linsolve
- [x] sympy/sympy#9628 no, solveset
- [x] sympy/sympy#9576
- [x] sympy/sympy#9674 no, new assumptions
- [x] sympy/sympy#9698
- [x] sympy/sympy#9700, no, I have better fix
- [x] sympy/sympy#9713
- [x] sympy/sympy#9671 no, complexplane
- [x] sympy/sympy#9720
- [x] sympy/sympy#9715
- [x] sympy/sympy#9328
- [x] sympy/sympy#9718 no, solveset
- [x] sympy/sympy#9716 no, solveset
- [x] sympy/sympy#9717 no, solveset
- [x] sympy/sympy#9708 no, solveset
- [x] sympy/sympy#9722 no
- [x] sympy/sympy#9710 no, solveset
- [x] sympy/sympy#9694 new bug, because you broke things before...
- [x] sympy/sympy#9726 linsolve
- [x] sympy/sympy#9724 no, solveset
- [x] sympy/sympy#9735 no, I don't have this silly helper
- [x] sympy/sympy#9732 yeah, why not
- [x] sympy/sympy#9678
- [x] sympy/sympy#8762
- [x] sympy/sympy#9736 no, solveset
- [x] sympy/sympy#9719 no, is this an exercise for kids?
- [x] sympy/sympy#2710 RealField () is a field?  I don't think so...
- [x] sympy/sympy#9749
- [x] sympy/sympy#9639 no, series
- [x] sympy/sympy#9696 no,   ConditionSet
- [x] sympy/sympy#9756 partially
- [x] sympy/sympy#7501 no, Mathieu functions
- [x] sympy/sympy#9760 no, new crappy place for handlers...
- [x] sympy/sympy#9757 no, badges
- [x] sympy/sympy#9752 no, physics
- [x] sympy/sympy#9199 no, I don't care about Floats.  Should go away
- [x] sympy/sympy#9711

### CODE REVIEW

**Comment by adbiks** [comment]
By looking at your comments it looks like as if you are God.

**Comment by skirpichev** [comment]
Why this does matter for you?  Anyway, if by whichever reason I'm God, I don't care about the flock...

**Comment by rigbiks** [comment]
It doesn't matter for me as long as I am not the contributor for this Project. I stumbled upon this repo by chance thought it to be the original repo, later discovered it'a a fork of sympy & I was amazed by your comments. Anyways I don't care, go at your will.

**Comment by skirpichev** [comment]
On Thu, Aug 13, 2015 at 12:42:54PM -0700, Adrian Ashley wrote:
>    I stumbled upon this repo by chance thought it to be the original repo

I'm sorry.  I will be glad if you can share any suggestions on
how to prevent this kind of misunderstanding in future.

>    I was amazed by your comments

Actually, this pr doesn't have any comments (except yours and my reply).

Perhaps, you are about my notes in the pr description.  These are
just for me, to distinguish things that are not acceptable for
inclusion (checkbox on means review was done).  Do you think
something is wrong with this?

**Comment by rigbiks** [comment]
Through comments, I mean the words you used for yourself, but eventually github is an open platform, so it means you are publicly disrespecting other's code. 

* `no, crap` 
* `no, new crap for series` 
* `no, new crap for new new assumptions` and etc

I mentioned you God, as you are solely judging the works of 100's (or maybe less) of developers.

**Comment by skirpichev** [comment]
On Fri, Aug 14, 2015 at 09:25:49AM -0700, Adrian Ashley wrote:
>    Through comments, I mean the words you used for yourself, but eventually
>    github is an open platform, so it means you are publicly disrespecting
>    other's code.

"Very bad code", "very bad idea" and so on - looks
better?  Perhaps, but really it's same.
 
>    I mentioned you God, as you are solely judging the works of 100's (or
>    maybe less) of developers.

To do review job you must be familar with the code (and with
the field, of course).  So, yes, I think I can judge their code,
at least just as well as any sympy developer.

Anyway, thank you for sharing your opinion.

btw,
https://groups.google.com/forum/#!topic/sympy/xEgWEcg6Puk
- you could use subs method here, instead of xreplace.

**Comment by rigbiks** [comment]
That was my mere intuition about these, so thought to share, though I may be wrong, since I am not an expert in this field.

> - you could use subs method here, instead of xreplace.

It may not work here:
```
>>> sin(exp(a*x)).subs({exp(x): x})
>>> sin(exp(a*x))
```

**Comment by skirpichev** [comment]
> It may not work here:

The problem is: what you want ("substitute mathematically") is not well defined enough.  What kind of transformations on the original expr tree are allowed and so on.  But in general, the idea of subs method is math-aware substitution, so it appears to be closest (On another hand, xreplace is stupid: replacements occur only if an entire node in the expr tree is matched).  Exactly your last example *may be* a bug (depends on assumptions on the `a` symbol).

Very flexible (but not elegant) solution may be the replace method, an example:
https://github.com/skirpichev/omg/blob/master/sympy/series/gruntz.py#L219
See the docstring of this method, e.g. p 3.1.

**Comment by rigbiks** [comment]
Alright, Nicely explained! Thanks! :)

**Comment by skirpichev** [comment]
Thank you for the [bugreport](#124) :)

BTW, now my "disrespecting" words may look more acceptable for you.  I think that core developers (all with answers in your thread, except Gaurav Dhingra and famous Richard Fateman) should know sympy's basics.  Unfortunately, their level is around "I am also Interested in getting the solution for this." (c)  And they have full commit access...

**Comment by aktech** [comment]
Hi @skirpichev 
Thanks for your criticism, I love to see my code being criticized, as that gives me some learning opportunity.

> Unfortunately, their level is around  "I am also Interested in getting the solution for this."

Do you have the solution for this? You don't since it's a bug then what do you think I should have said, when I don't know the solution, or didn't have the time to figure out it's a bug?
I am not an egoist, so I prefer asking others. That's how I have learnt most of the things I know in different domains.

> I think that core developers (...) should know sympy's basics

I am sorry, I am not good enough to understand half a million lines of code within a few months, considering the fact that, I am a student who has a lot of other stuffs to do as well.

> And they have full commit access...

So, you think, for having push access one should be aware of each and every nook and corner of the codebase? Unfortunately, it's not the case with 95% of open source projects which have some community around it, (except pet projects).

**Comment by skirpichev** [comment]
> I love to see my code being criticized

That's not just about the code.

> Do you have the solution for this?

Sure.  subs method.  (And suggested above workaround, while subs is still broken.)

> So, you think, for having push access one should be aware of each and every nook and corner of the codebase?

With basics of sympy, yes.  The question wasn't about the code at all...

**Comment by aktech** [comment]
>That's not just about the code.

Sure, you well know.

> Sure. subs method. (And suggested above workaround, while subs is still broken.)

The simple fact is that the following doesn't works, without actually fixing the bug in `subs`.

```python
In [5]: sin(exp(a*x)).subs({exp(x): x})
Out[5]: sin(exp(a*x))
```

> With basics of sympy, yes. The question wasn't about the code at all...

and, that made you conclude about my level of understanding.

Let me clear:
* I don't believe in unproductive argument, I rather believe in discussion.
* I do write crappy code, and I strive to improve by learning and 'asking'.
* I do see a lot of crappy code by others, but I rather believe in helping them improve rather than, pointing fingers and demotivating them.
* And last but not the least "I don't Judge people"

> BTW, now my "disrespecting" words may look more acceptable for you.

I am happy, atleast you agree your words are disrespecting. I dont' mind anyways I may write a better code tomorrow. I may have a better understanding tomorrow, but I will never have an incredible ability to judge people. Anyways Thanks for your comments.

**Comment by skirpichev** [comment]
On Wed, Aug 19, 2015 at 09:53:09AM -0700, AMiT Kumar wrote:
>      Sure. subs method. (And suggested above workaround, while subs is still
>      broken.)
> 
>    The simple fact is that the following doesn't works, without actually
>    fixing the bug in subs.

That's why I'm talking about workaround (with replace) too.

(BTW, the "following" is NOT the bug in subs.  It's a bug only
for some specified assumptions on "a".)

> and, that made you conclude about my level of understanding.

Have I options?

> I rather believe in discussion.

Until you don't like arguments of your opponent.  Then you ban him...

Relax.  There is no reviews (only end of it, i.e. either something
"good" or "bad"), so you can't "learn" here in the way you like.

>      BTW, now my "disrespecting" words may look more acceptable for you.
> 
>    I am happy, atleast you agree your words are disrespecting.

Please note quotes.

**Comment by aktech** [comment]
> Have I options?

You never have any, except your own opinions.

> Until you don't like arguments of your opponent.  Then you ban him...

Probably, they learnt it from you.


On Wed, Aug 19, 2015 at 11:00 PM, Sergey B Kirpichev <
notifications@github.com> wrote:

> On Wed, Aug 19, 2015 at 09:53:09AM -0700, AMiT Kumar wrote:
> > Sure. subs method. (And suggested above workaround, while subs is still
> > broken.)
> >
> > The simple fact is that the following doesn't works, without actually
> > fixing the bug in subs.
>
> That's why I'm talking about workaround (with replace) too.
>
> (BTW, the "following" is NOT the bug in subs. It's a bug only
> for some specified assumptions on "a".)
>
> > and, that made you conclude about my level of understanding.
>
> Have I options?
>
> > I rather believe in discussion.
>
> Until you don't like arguments of your opponent. Then you ban him...
>
> Relax. There is no reviews (only end of it, i.e. either something
> "good" or "bad"), so you can't "learn" here in the way you like.
>
> > BTW, now my "disrespecting" words may look more acceptable for you.
> >
> > I am happy, atleast you agree your words are disrespecting.
>
> Please note quotes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/skirpichev/omg/pull/116#issuecomment-132706738>.
>



-- 


*Amit Kumar*

**Comment by skirpichev** [comment]
On Wed, Aug 19, 2015 at 10:45:12AM -0700, AMiT Kumar wrote:
>    > Until you don't like arguments of your opponent. Then you ban him...
> 
>    Probably, they learnt it from you.

I don't ban anyone.  For sure, you learnt this "nice" policy
of management discussions somewhere else.

**Comment by aktech** [comment]
> I don't ban anyone.

Yeah, you don't, you simply lock the pull request, so that people can't
disagree you.

On Wed, Aug 19, 2015 at 11:51 PM, Sergey B Kirpichev <
notifications@github.com> wrote:

> On Wed, Aug 19, 2015 at 10:45:12AM -0700, AMiT Kumar wrote:
> > > Until you don't like arguments of your opponent. Then you ban him...
> >
> > Probably, they learnt it from you.
>
> I don't ban anyone. For sure, you learnt this "nice" policy
> of management discussions somewhere else.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/skirpichev/omg/pull/116#issuecomment-132731528>.
>



-- 


*Amit Kumar*

**Comment by skirpichev** [comment]
> Yeah, you don't, you simply lock the pull request, so that people can't disagree you.

Where?

**Comment by aktech** [comment]
> Where?

[sympy/sympy/pull/8538#event-213322050](https://github.com/sympy/sympy/pull/8538#event-213322050)

**Comment by skirpichev** [comment]
Locking was used here exactly for purpose it designed for: keep spam away.

Conversation wasn't blocked from anyone (as it looks from your "so that people can't disagree you"), only restricted to collaborators, and even mentioned "people" (Joachim) have had a lot of time to "disagree" (or, as in this case, to post a lot of garbage, aka discussion for discussion).

**Comment by aktech** [comment]
Banning was used for the same purpose it's designed for: Keep attackers away

Quote from Github:

> Blocking a user
You can block a user if they're not interested in Playing Nicely Together. 

I am not interested in further conversation, as It's unproductive. You keep up your knowledge with you & I will keep up mine. I don't expect to learn something productive here. Good bye!

**Unsubscribed**

**Comment by skirpichev** [comment]
On Thu, Aug 20, 2015 at 03:32:00AM -0700, AMiT Kumar wrote:
>    Banning was used for the same purpose it's designed for: Keep
>    attackers away

The difference is that unproductive conversation - an objective
qualification.  That's why nobody from the sympy group
objected agaist my position about Jo's messages.  (Worse,
similar behaviour from him was a repeatedly mentioned pattern, up to a
recent time.)

In turn, constructive (i.e. with examples of what's bad
and why) critique is not an attack (Are you afraid to show
examples?  Perhaps, because they make the difference clear).

Of course, you are free to mark anything as "attack" or like.  But
that's just your next manifestation of double standards and low
professionalism among sympy's devs.

PS: Instead of teaching me life here, you could fill the bugreport,
provided for you by user in the quoted maillist's thread.

**Comment by skirpichev** [comment]
Amazing,  After two years - sympy still has reported here bug and sympy devs don't bother even adding a bugreport to their issue tracker.

**Pull request merged**
