### PR TITLE
Set zoo.is_complex to True and zoo.is_real to False

### PR DESCRIPTION
**Pull request by skirpichev**
an alternative to https://github.com/sympy/sympy/pull/9040

### CODE REVIEW

**Comment by aktech** [comment]
I think these tests (or equivalent) should be retained.

```diff
-def test_complex_infinity_inequalities():
-    raises(TypeError, lambda: zoo > 0)
-    raises(TypeError, lambda: zoo >= 0)
-    raises(TypeError, lambda: zoo < 0)
-    raises(TypeError, lambda: zoo <= 0)
```

**Comment by skirpichev** [comment]
They are reverted in the second commit.

**Comment by aktech** [comment]
> They are reverted in the second commit.

Ah! I see that now.
Thanks.

**Comment by skirpichev** [comment]
Ok, I think this make sense.

**Pull request merged**
